# Generated by Django 5.2.6 on 2025-10-05 13:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True, help_text='Profile picture - can be either an uploaded file or a Cloudinary URL', null=True, validators=[accounts.models.validate_profile_picture]),
        ),
    ]
