# Generated by Django 5.2.6 on 2025-10-07 15:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile picture stored on Cloudinary', max_length=255, null=True, verbose_name='image'),
        ),
    ]
