# Generated by Django 5.2.6 on 2025-09-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='meal_count',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
