# Generated by Django 5.2.6 on 2025-09-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_mealplan_meal_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='days',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
