# Generated by Django 5.2.6 on 2025-09-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_mealplan_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='description',
            field=models.CharField(blank=True, help_text='A short description for the meal plan.', max_length=200),
        ),
    ]
