# Generated by Django 5.2.6 on 2025-10-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='spice_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mild'), (2, 'Spicy'), (3, 'Hot'), (4, 'Extra'), (5, 'Hell')], help_text='Spice level from 1 (Mild) to 5 (Hell). Leave empty for non-spicy items.', null=True),
        ),
    ]
