# Generated by Django 5.2.6 on 2026-01-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_alter_fooditem_image'),
    ]

    def create_standard_and_set_food_type(apps, schema_editor):
        FoodType = apps.get_model('food', 'FoodType')
        FoodItem = apps.get_model('food', 'FoodItem')
        MealPlan = apps.get_model('food', 'MealPlan')

        standard, _ = FoodType.objects.get_or_create(
            name='standard',
            defaults={'slug': 'standard', 'is_active': True},
        )

        # At this point food_type/density are still CharFields in DB; set to numeric id as string.
        FoodItem.objects.all().update(food_type=str(standard.id))
        MealPlan.objects.all().update(density=str(standard.id))

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(create_standard_and_set_food_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fooditem',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_items', to='food.foodtype'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='density',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_plans', to='food.foodtype'),
        ),
    ]
