# Generated by Django 5.2.6 on 2026-01-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_foodtype_fooditem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
